# The APGS shall provide a mechanism to validate APGS inputs prior to build
# Application packages generated by the APGS shall specify memory resource requirements
# Application packages generated by the APGS shall specify CPU resource requirements
# Application packages generated by the APGS shall specify storage resource requirements
